# Exported from Render on 2024-05-20T09:12:35Z
services:
- type: web
  name: Translator
  runtime: python
  repo: https://github.com/jagadesh2006/Translator
  plan: free
  envVars:
  - key: PORT
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 main.py
version: "1"
